### PR TITLE
Fix bugs occuring in PHP >= 7.4

### PR DESCRIPTION
**Pull request by zner0L**
When running this on PHP 7.4 I ran into some issues. This PR fixes the fatal errors, though I want to point out, all those undeclared variables give my quite a lot of warnings.

Sorry for the whitespace reformatting, my editor didn't like the previous style and I didn't fin a way to reconstruct it (in fact, I might add another PR to address the style issues and adhere to [PSR-12](https://www.php-fig.org/psr/psr-12/)).

### CODE REVIEW

**Review by andras-molnar — APPROVED** [review]
Thanks for catching the unused variable!

**Review by andras-molnar — APPROVED** [review]

**Review by andras-molnar — COMMENTED** [review]
match.php does not work with older versions of PHP

**Comment by zner0L** [comment]
Interesting, I don't really see why. What errors do you get and what versions of PHP do you use? I tested the changes with 7.3 onwards, since that is the lowest supported version. However, I found some additional bugs in the `match.php` when there are no GET attributes. That should be fixed now.

**Comment by andras-molnar** [comment]
The AWS instance I'm using has PHP 7.0.33 (cli) (built: Jan  9 2019 22:04:26) ( NTS )

Running the updated match.php with this old version created an internal server error (I haven't looked at the details on the backend, only looked at the client).

However, I realize now that the PHP update on my server is long overdue, and will update it and implement your code once I have some free time. Thanks again for debugging!

**Pull request closed without merging**
